export const FEEDBACK = {
  FILL: 'FEEDBACK_FILL',
  FEEDBACK_PENDING: 'FEEDBACK_PENDING',
  FEEDBACK_SUCCESS: 'FEEDBACK_SUCCESS',
  FEEDBACK_ERROR: 'FEEDBACK_ERROR'
}

export const HOMEPHOTOS = {
  HOMEPHOTOS_PENDING: 'HOMEPHOTOS_PENDING',
  HOMEPHOTOS_SUCCESS: 'HOMEPHOTOS_SUCCESS',
  HOMEPHOTOS_ERROR: 'HOMEPHOTOS_ERROR'
}

export const ADD = {
  ADD_PHOTO_PENDING: "ADD_PHOTO_PENDING",
  ADD_PHOTO_SUCCESS: "ADD_PHOTO_SUCCESS",
  ADD_PHOTO_ERROR: "ADD_PHOTO_ERROR",
  ADD_TEXT_DATA: "ADD_TEXT_DATA",
}

export const SEND_PHOTO = {
  SEND_PHOTO_PENDING: "SEND_PHOTO_PENDING",
  SEND_PHOTO_SUCCESS: "SEND_PHOTO_SUCCESS",
  SEND_PHOTO_ERROR: "SEND_PHOTO_ERROR"
}

export const DELETE_PHOTO = {
  DELETE_PHOTO_PENDING: "DELETE_PHOTO_PENDING",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_ERROR: "DELETE_PHOTO_ERROR"
}

export const GET_PHOTOS = {
  ADMIN: 'ADMIN',
  GALLERY: 'GALLERY',
  GET_PHOTOS_SUCESS: 'GET_PHOTOS_SUCESS',
  GET_PHOTOS_ERROR: 'GET_PHOTOS_ERROR'
}

